version: "3.9" 
 
services: 
  db: 
    image: postgres:latest 
    restart: always 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    env_file: 
      - ./server/.env 
  backend: 
    build: ./server 
    # command: node index.js
    command: npm run dev  
    restart: always 
    volumes: 
      - ./server:/app/backend 
    ports: 
      - "5000:5000" 
    env_file: 
      - server/.env 
    depends_on: 
      - db 
  client: 
    build: ./client 
    command: npm start 
    tty: true 
    ports: 
      - "3000:3000" 
    environment: 
      - CHOKIDAR_USEPOLLING=true 
    volumes: 
      - ./client:/app/frontend 
    depends_on: 
      - backend 
volumes: 
  postgres_data: